### PR TITLE
Update list-of-adopters.md

### PR DESCRIPTION
**Pull request by kayceesrk**
This PR adds projects under ocaml-multicore org that have adopted the CoC. Thank you.

### CODE REVIEW

**Comment by Sudha247** [comment]
Thanks very much, KC! Lockfree has adopted the CoC too. :) (https://github.com/ocaml-multicore/lockfree/pull/71) Do you think it makes sense to update it on this PR?

**Comment by kayceesrk** [comment]
Done. I've also sorted the list of adopters using the `sort` command on the raw markdown.

**Comment by kayceesrk** [comment]
Any updates on merging this @Sudha247?

**Review by Sudha247 — APPROVED** [review]
Thanks. Looks good to me. I'll wait to see if anyone has thoughts on sorting.

**Comment by pitag-ha** [comment]
LGTM as well. Sorting is definitely a good idea. Thanks!

**Review by mseri — APPROVED** [review]

**Pull request merged**
